openapi: 3.0.0
info:
  title: Sangue Mais API
  version: 1.0.0
  description: API para gestão de doações de sangue
servers:
  - url: http://localhost:3000
    description: Servidor de desenvolvimento
  - url: https://backendsanguemais.onrender.com
    description: Servidor de produção
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []
paths:
  /auth/register:
    post:
      summary: Criação de novo usuário
      description: Cria um novo usuário com base nas credenciais fornecidas.
      tags:
        - Auth
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: "João"
                senha:
                  type: string
                  example: "senha123"
                nivelAcesso:
                  type: string
                  enum: ["Adm", "Hemocentro"]
                  example: "Adm"
                hemocentroId:
                  type: string
                  example: "60d0fe4f5311236168a109ca"
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  nome:
                    type: string
                  nivelAcesso:
                    type: string
                  hemocentroId:
                    type: string
        '400':
          description: Requisição inválida
        '401':
          description: Usuário não autenticado ou não autorizado
        '500':
          description: Erro interno do servidor
  /auth/login:
    post:
      summary: Login de Hemocentro
      description: Realiza o login de um hemocentro.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: "Gabriel123"
                senha:
                  type: string
                  example: "abc123"
      responses:
        '200':
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  expiresAt:
                    type: string
                    format: date-time
                  refreshToken:
                    type: string
        '400':
          description: Requisição inválida
        '401':
          description: Usuário não encontrado ou senha inválida
        '500':
          description: Erro interno do servidor
  /auth/login/adm:
    post:
      summary: Login de administrador
      description: Realiza o login de um administrador.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: "Admin"
                senha:
                  type: string
                  example: "Admin"
      responses:
        '200':
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  expiresAt:
                    type: string
                    format: date-time
                  refreshToken:
                    type: string
        '400':
          description: Requisição inválida
        '401':
          description: Usuário não encontrado ou senha inválida
        '500':
          description: Erro interno do servidor
  
